sudo: true
language: node_js
env: TEST_SUITE=unit
node_js:
  - "5.6.0"
cache:
  directories:
    - node_modules
install:
  - npm install
notifications:
  email: false
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"

script: "npm run test"
